add_newline = true

continuation_prompt = '[ . ](fg:grey)'

format      = """
$directory\
$git_branch\
$git_status\
$conda\
$kubernetes\
[ ](bg:dir_back)[\ue0b4 ](fg:dir_back)\
\n\
$character\
"""

palette = 'default'

[palettes.default]
dir_icon   = '#eeeeee'
dir_back   = '#444444'
dir_path   = '#99bbdd'
dir_repo   = '#99bbdd'
git_back   = '#666666'
git_icon   = '#aaccee'
git_text   = '#88aadd'
git_conf   = '#ffaa88'
k8s_back   = '#446699'
k8s_icon   = '#bbddff'
k8s_text   = '#bbddff'
conda_back = '#669966'
conda_icon = '#ddffdd'
conda_text = '#ddffdd'

[directory]
style             = 'bg:dir_back fg:dir_path'
format            = "[ \ue5ff ](bg:dir_back fg:dir_icon)[$path ]($style)"
truncation_length = 3
truncation_symbol = '…/'
repo_root_format  = "[ \ue5fb ](bg:dir_back fg:dir_icon)[$repo_root]($repo_root_style)[$path ]($style)"
repo_root_style   = 'bg:dir_back fg:dir_repo bold'

[git_branch]
symbol = "\ue725"
style  = "fg:git_icon bg:git_back"
format = "[ \ue0ba](fg:git_back bg:dir_back)[ $symbol ]($style)[$branch ](fg:git_text bg:git_back bold)"

[git_status]
style      = "fg:git_text bg:git_back"
format     = "([$all_status$ahead_behind ]($style))[\ue0bc ](fg:git_back bg:dir_back)"
conflicted = ' [$count conflicts](fg:git_conf bg:git_back bold)'
staged     = " \ueadc [$count](fg:git_icon bg:git_back bold)"
deleted    = " \ueadf [$count](fg:git_icon bg:git_back bold)"
renamed    = " \ueae0 [$count](fg:git_icon bg:git_back bold)"
untracked  = " \ueb32 [$count](fg:git_icon bg:git_back bold)"
ahead      = ' ahead by [$count](fg:git_icon bg:git_back bold)'
behind     = ' behind by [$count](fg:git_icon bg:git_back bold)'
diverged   = ' ahead by [$ahead_count](fg:git_icon bg:git_back bold)| behind by [$behind_count](fg:git_icon bg:git_back bold)'

[conda]
symbol     = "\ue235"
style      = 'bg:conda_back fg:conda_icon'
format     = "([ \ue0ba](fg:conda_back bg:dir_back)[$symbol [$environment](bg:conda_back fg:conda_text bold)]($style)[\ue0bc ](fg:conda_back bg:dir_back))"

[kubernetes]
disabled = false
symbol   = "\U000f10fe"
style    = "bg:k8s_back fg:k8s_icon"
format   = "([ \ue0ba](fg:k8s_back bg:dir_back)[$symbol ]($style)[$context( ($namespace))](bg:k8s_back fg:k8s_text bold)[\ue0bc ](fg:k8s_back bg:dir_back))"
#detect_extensions = ["yml", "yaml"]

[character]
format         = "$symbol"
success_symbol = "[ > ](bold green)"
error_symbol   = "[ > ](bold red)"
